version: '3'
services:
  nginx:
    container_name: "nginx"
    build:
      context: ./docker/nginx
    depends_on:
      - php
    ports:
      - 80:80
    volumes:
      - ./:/src

  php:
    container_name: "php"
    build:
      context: ./docker/php
    ports:
      - 5173:5173
    volumes:
      - ./:/src
      - /src/node_modules
      - /src/vendor
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: mysql-host
    ports:
      - 13306:3306
    volumes:
    #  - ./mysql/data:/var/lib/mysql
      - ./docker/mysql:/var/lib/mysql
    environment:
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5
    ports:
      - 8888:80
    depends_on:
      - db
  
  l10dev-redis:
    image: redis:alpine
    container_name: "l10dev-redis"
    ports:
      - 16379:6379
